version: '3.8'


services:
    server:
        container_name: myproject
        build:
            context: .
            dockerfile: ./Dockerfile
        entrypoint: ["/entrypoint.sh"]
        volumes:
            - ./myproject:/app
            - ./staticfiles:/app/staticfiles
        environment:
            DEBUG: "False"
            SECRET_KEY: ${SECRET_KEY}
            CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}
            ALLOWED_HOSTS: ${ALLOWED_HOSTS}
       
volumes:
    static_volume: {}          