# Generated by Django 5.1.2 on 2025-08-24 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='moderationaction',
            new_name='moderation__target__deb4a3_idx',
            old_name='moderation_target_idx',
        ),
        migrations.RenameIndex(
            model_name='moderationaction',
            new_name='moderation__action_856f55_idx',
            old_name='moderation_action_idx',
        ),
        migrations.RenameIndex(
            model_name='moderationaction',
            new_name='moderation__created_6378e6_idx',
            old_name='moderation_created_idx',
        ),
    ]
